### ISSUE TITLE
Not working with long file names?

### ISSUE THREAD

**Issue by bendulum** [bradzacher/mysqldump#1]
I have tried it with a long filename of 127 characters and I get
`Error: ENOENT: no such file or directory, open 'C:\Development\xxxxxxx\data\dumps\1449492501532_dump_[categories|countries|contributor_roles|affiliation_types|subscription_types].sql'`

When I use a shorter name it works. 
Don't know if it's an issue in your package, just wanted to let you know!

**Comment by webcaetano** [comment]
Hi sir @bendulum, thanks for the feedback.

The follow error i think are in the line :149
https://github.com/webcaetano/mysqldump/blob/master/index.js#L149

As you can see is a simple `fs.writeFile` from **node fs** core module.
