### ISSUE TITLE
Streamable output so that it can be piped

### ISSUE THREAD

**Issue by Serializator** [bradzacher/mysqldump#103]
At the moment it seems by quickly looking at the documentation (which is really easy to comprehend, kudos for that) that there is no support to stream the output from the MySQL dump. It's either output it to file or an object.

Streaming the output would increase extensibility and reduce memory usage as I could simply pipe it to wherever I want. Whether it be an SSH connection or simply `process.stdout` to give more flexibility in the space of piping using Bash.

If I missed something I'd be really happy but otherwise I think this might be a good addition to the library.

**Comment by tylangesmith** [comment]
+1 for this feature, it was the only thing stopping me from using this project 😢

**Comment by tigerwill90** [comment]
+1 this would be really useful for my use-case

**Comment by Serializator** [comment]
I think that this feature would deprecate `dumpToFile` and underwater pipe the readable stream to the writeable stream from `fs.createWriteStream`, this way the complexity to maintain both options (as long as `dumpToFile` stays deprecated) is minimised as much as possible.

**Comment by enricodeleo** [comment]
+1 absolutely useful for backup tasks like saving on S3/scp/dropbox/whatever
