### ISSUE TITLE
Where filter 

### ISSUE THREAD

**Issue by alifnaufalyasin** [bradzacher/mysqldump#106]
if i want to filter data for spesific row but it takes many 'where' in the same row id, how to filter it. 

Example : i want to get data where student_id = 5 and student_id = 6 in scoring row. so the result is scoring row from both student. it can be 2 student or more that i want to filter it

**Comment by bradzacher** [comment]
Check out the options in the readme.

https://github.com/bradzacher/mysqldump#options

I can't remember the exact config, but it's something along the lines of

```js
mysqldump({
  ...options,
  data: {
    where: {
      tableName: 'student_id = 5 AND student_id = 6',
    },
  },
});
```

**Comment by alifnaufalyasin** [comment]
i didnt see that config, in readme just 
`where?: {
        [k: string]: string;
    };
`
in #14 i just see 1 condition there. i was try with 'AND' , and didn't work

**Comment by bradzacher** [comment]
> in readme just 
> `where?: {
>         [k: string]: string;
>     };
> `

Yes, but the comment above it explains what it means

> A map of tables to additional where strings to add.

If the docs aren't clear enough, happy to accept a PR to improve the text.

---

The tool just concatenates the string you provide into the query. It should just work.

https://github.com/bradzacher/mysqldump/blob/develop/src/getDataDump.ts#L155

---

Could you give me some more information than "it didn't work"?

Help me to help you.

**Comment by alifnaufalyasin** [comment]
its works now. thank u for your information. nice to use this for backup my database easily

**Comment by alifnaufalyasin** [comment]
btw, how to insert if not exist, is there any option to do that?
