### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by Aspie96** [bradzacher/mysqldump#11]
When the database is not available, mysqldump throws an exception and stops the server.
Instead, it should call the callback function, giving the error as a parameter.

**Comment by webcaetano** [comment]
I'll take a look on that soon

**Comment by Aspie96** [comment]
Thank you very much.
There are cases when this may be a major problem.

Please, let me know if you correct the issue in a new NPM release.

Thank you again.

**Comment by bradzacher** [comment]
fixed #44 - uses promises now
