### ISSUE TITLE
mysqldump hangs occassionally

### ISSUE THREAD

**Issue by JoshuaHintze** [bradzacher/mysqldump#111]
I have a database backup server running where I will run multiple node processes on a crontab using mysqldump. I've noticed that sometimes mysqldump will have an issue that gets logged to console.error() but then never returns which seems to hang the entire nodeJs process. 

Each process is logging data to seperate folders but occasionally I will see the following logs

Starting Job: DB1  hourly backup
Error: ENOENT: no such file or directory, open '../db1/hourly/2020-10-03T21:00:00.008Z.sql.gz.temp'

I've looked through the code and I believe this is part of the cleanup after compressing. However I'm not sure where it is hanging. Any thoughts? I've added console logs before and after the call to mysqldump() and the after never gets called when I see this error message.

**Comment by nimesha95** [comment]
Experiencing the same issue. Any updates?

**Comment by JoshuaHintze** [comment]
The thing that stinks is I'm not even sure how to detect when this hangs. Since I can't catch this exception. Some of my databases take over an hour to backup so creating a timeout system would be difficult.

**Comment by bradzacher** [comment]
Happy to accept some help investigating this.
I don't use this tool myself any more since I left my last company.

I never ran into hangs myself when using. So I'm not sure what the problem might be.

**Comment by JoshuaHintze** [comment]
I would be happy to help if you could assist me a little bit. Just looking through the code, in my case I am doing a compression. 

Looking at the error it seems to be happening when it is cleaning up the temporary file called here:

https://github.com/bradzacher/mysqldump/blob/86992edc49671f99a1d7f8261c055800ea1eb59e/src/compressFile.ts#L42

Then it is being unlinked here:

https://github.com/bradzacher/mysqldump/blob/86992edc49671f99a1d7f8261c055800ea1eb59e/src/compressFile.ts#L11

Now why it doesn't exist, I have no clue yet. But you do try / catch it so you would think it would be ok....however this might be the key. Perhaps the file never got created, the connection to the database was never established or something. In any case entire mysqldump() function is in a try / finally. The finally does this.

DB.cleanup();

```
    public static async cleanup(): Promise<void> {
        await Promise.all(
            pool.map(async p => {
                await p.end();
            }),
        );
    }
}
```

My guess is we are awaiting the Promise.all() forever. Its the only thing that would make sense to me?

I can get this to consistently happen in 2-3 days of waiting. If I was to add some additional code would it make sense to log out the pool connections?

**Comment by bradzacher** [comment]
Essentially this is how it works when dumping to file only:
1) initialise empty destination file
1) open connection to the DB `#1`
1) fetch the schema
1) dump the schema to the file
1) fetch the triggers
1) kill the db connection `#1`
1) fetch the data
    1) open connection to the DB `#2`
    1) (if configured) lock tables
    1) fetch one table's data
    1) stream it to the file every `N` rows
    1) if more tables, goto `iii`, else continue
    1) (if configured) unlock tables
    1) kill the db connection `#2`
    1) flush the write stream to ensure all the inserts are written
1) dump the triggers to the file
1) (if configured) compress file
    1) rename the schema file to `XXX.temp`
    1) gzip stream the file, reading from `XXX.temp` and writing to `XXX`
    1) delete `XXX.temp`
1) ensure all DB connections are cleaned up

Every step is guarded so errors shouldn't cause any problems, unless there is a missing cleanup.
For example - the error you've listed should kill the entire `compressFile` function, and then the entire process should continue to the next step (which is just finishing up and cleaning up).

----

Does this only happen when you're using the `compressFile` option?

It might be worth running the script in node debug mode so you can attach a debugger when it locks up to see exactly where it locks up.

https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by JoshuaHintze** [comment]
Thank you @bradzacher  - I have my server setup running with inspect mode. I'm not sure if it is only compressFile mode. If I can't figure out where it locks up with the --inspect i'll try it without.....now we wait for it to freeze :)

**Comment by JoshuaHintze** [comment]
@bradzacher - Well I got it to hang with --inspect enbled.

Unfortanetly I'm not sure we will gather much information. Looking at where the code is operating it continously runs some internal nodejs code. For example here is a couple of step's through the event loop

```
break in timers.js:222
 220 function processTimers(now) {
 221   if (this[owner_symbol])
>222     return unrefdHandle(this[owner_symbol], now);
 223   return listOnTimeout(this, now);
 224 }
debug> o
break in timers.js:227
 225
 226 function listOnTimeout(handle, now) {
>227   const list = handle._list;
 228   const msecs = list.msecs;
 229
debug> o
break in timers.js:223
 221   if (this[owner_symbol])
 222     return unrefdHandle(this[owner_symbol], now);
>223   return listOnTimeout(this, now);
 224 }
 225
debug> o
break in timers.js:227
 225 
 226 function listOnTimeout(handle, now) {
>227   const list = handle._list;
 228   const msecs = list.msecs;
 229
debug> o
break in timers.js:223
 221   if (this[owner_symbol])
 222     return unrefdHandle(this[owner_symbol], now);
>223   return listOnTimeout(this, now);
 224 }
 225
debug> o
break in internal/process/next_tick.js:42
 40
 41   function _tickCallback() {
>42     let tock;
 43     do {
 44       while (tock = queue.shift()) {
```

I tried setting some breakpoints in my actual code but it never hits those. I'm not sure exactly what to do next other than restart it with breakOnException debugging and see what happens there.

**Comment by JoshuaHintze** [comment]
Ok, so one thing I did learn is that in the past I ran this node process using pm2,  in cluster mode. This made it so that the same process was scaled to the number of CPU cores and it handles things like incoming api requests and round robins them, etc.

Instead, I launched 4 independent pm2 processes and the effect was that the program would still give the same error, but in this case it would die and restart. It's not exactly the best scenario but atleast my server doesnt lock up. The adverse effect is that the SQL dump at that point is lost it seems or zero bytes.

I'm going to try disabling compression and see if that stops all issues. If that is the case I'll just write my own gzip compression after the fact.

**Comment by JoshuaHintze** [comment]
Ok, I removed the gzip compression and now all 4 processes have yet to restart or throw an exception for the last 32 hours. Prior to this they would fail in 2-7 hours time when doing a backup once an hour.

For now I'll just do my own gzip compression on the files.

**Comment by bradzacher** [comment]
I'm not sure why the compression would fail. There's nothing special about what it does - it's fairly straightforward code.

Maybe there's some conflict with the system somewhere that causes the temporary file creation to fail? I'm not sure!
Regardless - it doesn't do anything special with compression so it should be trivial to add a few steps to the script to pipe the file into a tarball after it completes.

**Comment by JoshuaHintze** [comment]
Yeah to be honest I'm not sure either. I'll most likely just do a child_process : spawn / exec to call gzip for my own needs. Thanks for putting this library together.

**Comment by alaindeurveilher** [comment]
I think I spotted the problem, or at least a quickfix/workaround fix, as described in my coment in similar issue #119
