### ISSUE TITLE
How to dump multiple schemas, like --all-databases flag on mysqldump

### ISSUE THREAD

**Issue by ddonahoevibrenthealth** [bradzacher/mysqldump#113]
I saw another issue asking about this and the response was "read the documentation" but I don't see any info on it. 

https://github.com/bradzacher/mysqldump/issues/58

Is there a way to dump multiple databases/schemas into a single file similar to

`mysqldump --user=[USER] --password=[p --host=[HOST] --all-databases > dumpfile.sql`

?

Thanks!

**Comment by bradzacher** [comment]
The readme explains how to use this library - it's API with examples.

You have to write a script which uses the API.
