### ISSUE TITLE
InnoDB --single-transaction option

### ISSUE THREAD

**Issue by Igor-Lopes** [bradzacher/mysqldump#115]
Does it support --single-transaction option for large databases?

**Comment by bradzacher** [comment]
Support how? Could you please explain what you're asking for exactly?

**Comment by Igor-Lopes** [comment]
Yes, sure. 

I couldn't find `--single-transaction` or any equivalent option in `DumpOptions` Interface. It can be very useful for large database with active reads and writes.

_"no changes that occur to InnoDB tables during the dump will be included in the dump". So, effectively, the dump is a snapshot of the databases at the instant the dump started, regardless of how long the dump takes."_

Please, see: [https://stackoverflow.com/questions/41683158/mysqldump-single-transaction-option](https://stackoverflow.com/questions/41683158/mysqldump-single-transaction-option)

**Comment by bradzacher** [comment]
No it does not have support. Happy to accept a PR.
