### ISSUE TITLE
how to close connection?

### ISSUE THREAD

**Issue by applemate** [bradzacher/mysqldump#118]
I let this script run every day, after about 30 days, my system crash due to manny connection. So Is there a way to close finished connections ?

**Comment by bradzacher** [comment]
All connections should be closed automatically. If they're not, it's a bug.

All of our tests are working fine and leak no connections.

If you can create a repro case, then we can look into this. Otherwise nit a whole lot we can do.

**Comment by applemate** [comment]
This is the repo.

https://github.com/craigcosmo/backup

This just basically dump the db and save the sql dump file to my dropbox
