### ISSUE TITLE
Err creating the backup with the compressFile option

### ISSUE THREAD

**Issue by Devshail** [bradzacher/mysqldump#119]
![image](https://user-images.githubusercontent.com/34369310/106557168-4040bd00-6547-11eb-984a-8446c49ab130.png)
I have created a db backup cronjob. previously it was working fine but now its giving error

```js
for (let index = 0; index < dbOptions.length; index++) {
                let date = new Date();
                currentDate = this.stringToDate(date);
                const element = dbOptions[index];
                if (element.autoBackup) {
                        con = {
                                host: element.host,
                                user: element.user,
                                password: element.pass,
                                database: element.database,
                        }
                        fName = element.database + '-' + currentDate.getHours() + '_' + currentDate.getMinutes() + '-' + currentDate.getFullYear() + '-' + (currentDate.getMonth() + 1) + '-' + currentDate.getDate() + '_dump.sql.gz';
                        name = backupDirPath + '/' + fName;
                        console.log('starting bakup',name);
                        await mysqldump({
                                connection: con,
                                dumpToFile: name,
                                compressFile: true,
                        }),then(async (res)=>{
                                await this.uploadFile(fName, element.bPath);
                        }).catch(error=>{
                                console.log(error)
                        });
                        console.log('end backup');
                        console.log('upload start');
                }
        }
        return;
```

```js
exports.uploadFile = async (fileName, key) => {
        // Read content from the file
        console.log('reading file');
        const fileContent = fs.readFileSync(backupDirPath + '/' + fileName);
        console.log('file readed');
        // Setting up S3 upload parameters
        const params = {
                Bucket: bucket,
                Key: key + '/' + fileName, // File name you want to save as in S3
                Body: fileContent
        };
        // Uploading files to the bucket
        console.log('uploading...');
        await s3.upload(params, function (err, data) {
                if (err) {
                        throw err;
                }
                console.log(`File uploaded successfully. ${data.Location}`);
        }).promise();
        console.log(fileName);
        console.log('uploaded!');
};
```

**Comment by bradzacher** [comment]
I mean... Nothing has changed from this side (no releases in a while), so if it's recently just stopped working - it's likely something on your end?

**Comment by Devshail** [comment]
It was working fine but now it broken. I am not able to identify why this is happening now 
you can check complete code here

https://github.com/Devshail/Database-backup-scheduler

**Comment by bradzacher** [comment]
again - we haven't done a release in over 6 months. So if something has started happening recently - likely something on your end.

there's absolutely no way for me to reproduce your dev environment - so there's no way for me to reproduce this for you, so you'll have to help debug and look into this.

**Comment by Devshail** [comment]
can you please do this in Linux environment  I am facing issue over there

**Comment by bradzacher** [comment]
I do not have access to a linux environment.

> you'll have to help debug and look into this.

**Comment by Kosta-Github** [comment]
I observed the same thing 2-3 weeks ago. We are using an alpine based docker image and installing the latest node 14.x version in it. Since I cannot reproduce this issue on my dev system (outside of a docker container) I tend to assume that alpine is the issue here.
But since we are migrating away from MySQL we didn‘t invest in tracking down the root cause but  implemented the workaround to use uncompressed backups and then stream compress them on the fly while uploading to S3...

**Comment by omundy** [comment]
I have this issue too, on my localhost (Mac, node v15.6.0) and my production server (Ubuntu) as of 5 days ago. It has been working for a while but I just noticed the problem.

```bash
node:events:356
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open './db_20210222.sql.gz.temp'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './db_20210222.sql.gz.temp'
}
```
Code below

```js
const result = await mysqldump({
			connection: {
				host: Config.database.host,
				user: Config.database.username,
				password: Config.database.password || "",
				database: Config.database.name,
			},
			dump: {
				schema: {
					table: {
						dropIfExist: true
					}
				}
			}, 
			dumpToFile: path + filename,
			compressFile: compress,
		});
```

**Comment by omundy** [comment]
**Update**: The issue is with the compressFile option. If I omit this param (default: false) then the dump to `.sql` performs without error.

**Comment by alaindeurveilher** [comment]
I noticed this issue on my side as well, by reusing the function `compressFile` in my code. The issue @bradzacher is that in the `deleteFile` function, sometimes for some reason the file to delete does not exists, so the unlink fails, and for some reason I don't understand, the catch does not work. So my suggestion is to first check the existence of the file before the unlink:


from currently:

```javascript
function compressFile(filename: string): Promise<void> {
//...
  const deleteFile = (file: string): void => {
    try {
      fs.unlinkSync(file);
    } catch (_err) {
      /* istanbul ignore next */
    }
  };
// ...
}
```

change to:

```javascript
function compressFile(filename: string): Promise<void> {
//...
  const deleteFile = (file: string): void => {
    try {
      if (fs.existsSync(file)) { // <-- FIX IS HERE
        fs.unlinkSync(file);
      }
    } catch (_err) {
      /* istanbul ignore next */
    }
  };
// ...
}
```

Regards,

**Comment by alaindeurveilher** [comment]
Same issue as #111

**Comment by alaindeurveilher** [comment]
The reasons why the error is not caught in the catch block could have been given in this comment:
https://github.com/nodejs/node/issues/9455#issuecomment-258315799

The comment is dated from Nov. 2016. I don't know if something has been done since then, but apparently, it is originated in the 'stream' library (probably called internally by the fs.unlinkSync method) which would try to stat the file after it has been deleted. Anyway, wrapping this line with the if condition might be a good solution for now.
