### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by ghost** [bradzacher/mysqldump#12]
There is multiple error when we try to IMPORT the .sql file.

For me : 
First try --> #1005 - Can't create table `xibo2`.`blacklist` (errno: 150 "Foreign key constraint is incorrectly formed") 

So after I try again with the box "checking for foreign key" not active !!
Second try --> #1416 - Cannot get geometry object from data you send to the GEOMETRY field

And when I export a sql file with MyPhpAdmin it works perfect.
I think it need some updates.

**Comment by bradzacher** [comment]
fixed #44 - geometry is now properly supported, and foreign key checks are disabled
