### ISSUE TITLE
mysqldump not work with pm2 

### ISSUE THREAD

**Issue by Raeddeyeh** [bradzacher/mysqldump#121]
when run mysqldump via pm2  on server the pm2 restart automatic

**Comment by bradzacher** [comment]
You need to give me more information.

What are you doing?
What's not working?
What's pm2?

**Comment by Raeddeyeh** [comment]
thanks for your reply 

I have an issue when dopy my code on the server running over pm2 (process manager for production Node.js applications)

the same code creating dump on locally 

* local
![1111111](https://user-images.githubusercontent.com/7623554/113620942-a9d26a00-9663-11eb-988c-7f776f834493.png)

* server 
![22222](https://user-images.githubusercontent.com/7623554/113620953-ae971e00-9663-11eb-8e27-a65ac9a978b1.png)

**Comment by Raeddeyeh** [comment]
in the server dump export  like this

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

**Comment by bradzacher** [comment]
I don't know what pm2 is nor how it works.
Nor do I know how your script works.

Again - ***I NEED MORE INFORMATION***.

# HELP ME TO HELP YOU.

**Comment by Raeddeyeh** [comment]
try {
  await mysqldump({
    connection: {
      host: dbHost,
      user: dbUser,
      password: dbPassword,
      database: dbName,
    },
    dumpName: './' + dumpName,
  });
    console.log("Database backup successfully created.");
} catch (error) {
  
  console.log(error)
}




dumpfile output : 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;



What are the possible reasons for this output? 

Thank you in advance for your support

**Comment by Raeddeyeh** [comment]
UPDATE : solved 

 pm2 will restart the process because new file content is detected and stop the script to write on the dump file 
 
 must stop pm2 --watch to avoid restart
