### ISSUE TITLE
Include the name of the schema in the dump

### ISSUE THREAD

**Issue by alaindeurveilher** [bradzacher/mysqldump#122]
Hello,

The generated dump does not contain the name of the schema beeing dumped.

It seems to me that there is no option to include the name of the schema in the dump file, or that the current documentation of the API is not very explicit about that option. 

I would like to have in my dump, for instance:

```mysql
CREATE DATABASE /*!32312 IF NOT EXISTS*/ `my_schema` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `my_schema`;

...
```

Is there a way to do it with the current version, or is it a limitation?

If there is no option available, it would be very helpful to add such an option, otherwise, I would loose the possibility to compressFile .
I would prefer to avoid to manually: have to dumpToFile, then fs edit the file, prepend the create database/use statements, close the file, and zip the file.

Thank you very much.

**Comment by bradzacher** [comment]
No there is no option to do this.

> I would prefer to avoid to manually: have to dumpToFile, then fs edit the file, prepend the create database/use statements, close the file, and zip the file.

This is literally all that the tool does though. It dumps to a temporary file then zips the file and deletes the temporary file.. so you wouldn't really lose anything zipping yourself...

**Comment by alaindeurveilher** [comment]
Ho, alright thank you then. I will do that then as a quick fix on my code.
On my free time, I could try to find and propose an improvement then (pull request).

Thank you.

Feel free to close, if this stays open for too long.

**Comment by alaindeurveilher** [comment]
Same as #67 apparently
