### ISSUE TITLE
Compressed output?

### ISSUE THREAD

**Issue by ybrodsky** [bradzacher/mysqldump#13]
Is there some option to compress the output, for example backup.sql.tar / backup.sql.gz?

**Comment by webcaetano** [comment]
Thats a good idea. 
I'll make a `minor` for that soon.

**Comment by tbadaczewski** [comment]
I'd really love compression as well.

**Comment by bradzacher** [comment]
To reduce memory usage, the file gets streamed directly to the disk as data is read from the db.
This means we don't have a file in memory to be able to compress.

Could look add this as an option, but for now its easy to add as a step after the dump.
something like...
```TS
await mysqldump({ dump: { returnFromFunction: false }, dumpToFile: filename })
const rawSql = fs.readFileSync(filename)
const gzSql = zlib.gzipSync(rawSql)
fs.writeFileSync(`${filename}.gz`, gzSql)
```

**Comment by Kosta-Github** [comment]
see https://github.com/bradzacher/mysqldump/pull/69

**Comment by Kosta-Github** [comment]
@bradzacher can be closed now, since released in: https://github.com/bradzacher/mysqldump/releases/tag/3.1.0
