### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by bduff9** [bradzacher/mysqldump#131]
Hello!  Trying to use this plugin but it throws an access denied error when running:

```
[2021-06-19T20:06:53.274Z] Exception: Error: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
[2021-06-19T20:06:53.274Z] Stack: Error: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```

Seems to be schema-related as it can output triggers and data but fails anytime I include the schema (i.e. schema is not false).  I already have max permissions on this MySQL instance (I'm on shared hosting) so cannot increase them anymore and unsure what is even needing the extra permissions.

FWIW, I can run a regular mysqldump command without issue.  But need to be able to do so in a serverless node env, which is why I am looking at this tool.  Do you happen to have any ideas for how I can get this to work?

EDIT: This is how I'm trying to running it currently:
```
await mysqldump({
		connection: {
			database,
			host,
			password,
			port: +port,
			user: dbuser,
		},
		dump: {
			data: {
				lockTables: true,
				verbose: true,
			},
			schema: {
				engine: false,
				table: {
					dropIfExist: true,
				},
			},
			trigger: false,
		},
		dumpToFile: dumpFile,
	});
```

As mentioned, I have tried playing with a lot of the variables to disable things, and the only thing that seems to let it work is setting `schema: false,` above.  This outputs the data still, but I need the full table structures so would like to get that working if at all possible.

**Comment by bradzacher** [comment]
I'm no DB expert, so I'm not sure what it could be.
Best bet would be to look at the commands we run.

https://github.com/bradzacher/mysqldump/blob/66839a57e572a07c046b0ba98753f30a7026cbd8/src/getDataDump.ts#L106-L107
https://github.com/bradzacher/mysqldump/blob/66839a57e572a07c046b0ba98753f30a7026cbd8/src/getDataDump.ts#L158
https://github.com/bradzacher/mysqldump/blob/66839a57e572a07c046b0ba98753f30a7026cbd8/src/getDataDump.ts#L209-L210
https://github.com/bradzacher/mysqldump/blob/66839a57e572a07c046b0ba98753f30a7026cbd8/src/getSchemaDump.ts#L34
https://github.com/bradzacher/mysqldump/blob/66839a57e572a07c046b0ba98753f30a7026cbd8/src/getTriggerDump.ts#L60

**Comment by bduff9** [comment]
Just to verify, all of those commands are run for the schema dump only?  I did already go through your source before opening this ticket and saw 3 different commands that seem to be run to get the schema dump: 

```
SHOW CREATE TABLE table;
SHOW FULL TABLES FROM schema;
SHOW COLUMNS FROM table FROM schema;
```

All 3 of these I can run just fine against this database.  I will try some of the other ones you listed above, but they seem to be focused around the trigger and data dumps, which are working correctly.

**Comment by bradzacher** [comment]
In a nutshell all the code does is this:
```ts
import * as mysql from 'mysql2/promise';

const options = merge({
  host: 'localhost',
  port: 3306,
  user: '',
  password: '',
  database: '',
  charset: 'UTF8_GENERAL_CI',
  ssl: null,
}, theOptionsYouPassIn, {
  multipleStatements: true
});

const connection = await mysql.createConnection(options);
```

Then we run the queries. That's it.
No other magic or wizardry.

For a schema dump again we literally just run `SHOW CREATE TABLE <table name>`.
No other magic.

If it's not working then there's likely something wrong with your setup.
But I'm no DBA so I don't have really any experience to lean on here.
