### ISSUE TITLE
Blobs are not dumped correctly

### ISSUE THREAD

**Issue by loilo** [bradzacher/mysqldump#17]
When I try to dump tables with blobs, the module is going to generate MySQL syntax errors by adding an additional single quote before the value.

Example:
BLOB Value: `613a303a7b7d`
Output in INSERT statement:

```
[...] '1',NULL,'',NULL,NULL,''613a303a7b7d',NULL [...]
                             ^
```

This leads to problems with exporting BLOB-including tables.

**Comment by webcaetano** [comment]
Thanks for reporting i`ll check soon.
