### ISSUE TITLE
Callback doesnt fetch error.

### ISSUE THREAD

**Issue by ManpreetGulati** [bradzacher/mysqldump#28]
![dbdump_errorlog](https://cloud.githubusercontent.com/assets/11961915/25488035/8c18e164-2b83-11e7-850a-0199df1aad20.PNG)
Callback function  doesnt fetch "err". It enters "else" in case of no error but doesnt enter if condition when error is thrown. "err" is always null.

**Comment by bradzacher** [comment]
should be fixed by #44.
we use promises now
