### ISSUE TITLE
npm module to upload mysql dump into new database

### ISSUE THREAD

**Issue by prashanthmadi** [bradzacher/mysqldump#3]
is there a npm module to upload this dump into new database ?

**Comment by webcaetano** [comment]
https://github.com/felixge/node-mysql

```
var connection = mysql.createConnection({multipleStatements: true});

connection.query(fs.readFileSync('yourFile.sql'), function(err, results) {

});
```

Should work.

<sub><strong>Based on http://stackoverflow.com/questions/22276763/use-nodejs-to-run-an-sql-file-in-mysql?answertab=active#tab-top</strong></sub>

A .sql dump file is just multiple sql queries.
I usually just copy-and-pasta the file contents and run it.
