### ISSUE TITLE
I got empty files every time when dumping

### ISSUE THREAD

**Issue by igorjos** [bradzacher/mysqldump#31]
Using code like this:
```

mysqlDump({
		host: 'localhost',
		user: 'root',
		password: '',
		database: 'databasename',
		dest:'./db1-dump.sql' // destination file 
	},function(err)
	{
		// create data.sql file; 
		if(err)
		{
			console.log('Error:', err);
			return;
		}
		
		console.log('Result: status done');
	});
```

I get no errors on Windows 8.1, but exported file is always empty.
I make sure that mysql and mysqldump are set to path in case this script uses them but nothing has changed the output.

Mysql version I have is from XAMPP

**Comment by Alutun** [comment]
Got the some issue here, working well while running the script on LINUX or OSX

**Comment by sanket-rebelute** [comment]
what should we do on windows?

**Comment by Lakshya31** [comment]
Was facing the same issue on windows when i was trying to store the backup file with the filename as a string conversion of new Date() object. It seems the problem subsided when I separated each component of time ( like date from getDate(), time from getTime, etc. ) then concatenated everything with a "-". I'll attach the snippet for both cases of working vs not working:

Working:

```
let newDate = new Date();
let file = parseInt(newDate.getMonth()+1)+'-'+newDate.getDate()+'-'+newDate.getFullYear()+'-'+newDate.getTime();
file = "./backup/"+file + ".sql";
        
mysqldump({
    connection: {
        host: this.host,
        user: this.user,
        password: this.password,
        port: this.port,
        database: this.db,
    },
    dumpToFile: file,
})
```


Not Working :

```
let newDate = new Date();
let file = newDate.toString();
file = file.slice(0,file.length-5);
file = "./backup/"+file + ".sql";
        
mysqldump({
    connection: {
        host: this.host,
        user: this.user,
        password: this.password,
        port: this.port,
        database: this.db,
    },
    dumpToFile: file,
})
```



I don't know if this will help or not, but I felt like I should inform.

**Comment by bradzacher** [comment]
I'm going to close this, as the original issue should be gone from the 2.0 rewrite.
