### ISSUE TITLE
Support ssl connection options to connect tot Azure Mysql and Amazon RDS.

### ISSUE THREAD

**Issue by daniel-jirca** [bradzacher/mysqldump#42]
It would be great if the connection would support a ssl option, to be able to dump databases over encrypted connection.
The Azure Mysql service and Amazon Mysql instances support connectivity over ssl:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.SSLSupport
https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl
Without this option the application crashes with the following error when trying to connect to Azure Mysql with ssl option turned on:
```
SHOW TABLES FROM `xxxxx` Error: UNKNOWN_CODE_PLEASE_REPORT: SSL connection is required. Please specify SSL options and retry.
```

**Comment by bradzacher** [comment]
SSL should be supported now, just pass the config along with the rest of the `connection` config you pass in.
