### ISSUE TITLE
Add header flags to the string output

### ISSUE THREAD

**Issue by bradzacher** [bradzacher/mysqldump#48]
The dumped SQL file has a set of session variables before and after the dump to do things like disable foreign key checks.

The string that is returned from the function (i.e. in-memory dumping) doesn't include those same variables.

This means that in a lot of cases you can't just run the output that is returned from the function, which makes it kind of useless.

**Comment by alaindeurveilher** [comment]
I face the same issue when trying to workaround the #67 and #122, and I noticed that these session variables are missing from the DumpReturn schema and data. (I wanted to concatenate these 2).

Example:

```mysql

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

...
```

Those information are not really part of the schema, nor the data (neither the orther current fields: trigger, table, etc.

I think this fix, if feasible, would require a new field of DumpOptions.
