### ISSUE TITLE
Error when using JSON column type

### ISSUE THREAD

**Issue by lhaley2011** [bradzacher/mysqldump#49]
https://github.com/assignar/mysqldump/blob/2473a6d2cf55db739b8d6a3739b2ede30ddac30c/src/resolveType.ts#L14

It fails to work with json column types. I believe 'json' needs to be added here. Adding locally seems to resolve the issue.

**Comment by tomskip123** [comment]
just a short comment thought i might add. 

Temporarily use this package to make an, un-advised, monkey patch. really helpful module https://github.com/ds300/patch-package. 

great short term solution for time dependent features

**Comment by donpaul120** [comment]
I'm also having this issue.... can't dump tables that have json columns

**Comment by fjeddy** [comment]
Same here!

**Comment by lhaley2011** [comment]
https://github.com/bradzacher/mysqldump/pull/57
