### ISSUE TITLE
Dump file complete event

### ISSUE THREAD

**Issue by pmkroeker** [bradzacher/mysqldump#55]
When dumping a large-ish database, is there an event that fires when the dump file has been created. I am currently using a file watcher, but it fires when the file has been created and not when all the data is in the file.

Is there an accepted way to do this?

**Comment by Dafrok** [comment]
Why not use callback function?

**Comment by pmkroeker** [comment]
Where would I put it? As far as I can see the documentation does not show the placement of a callback. I could have missed it, if so a reference would be appreciated. I think what I might do is await the return and write the dump file myself.

**Comment by Akamaozu** [comment]
@pmkroeker

Try this

```
mysqldump( options )
  .then( function(){
      // should be done now.
  })
  .catch( (e) => throw e )
  

```

**Comment by pmkroeker** [comment]
Yep thanks that's what I ended up doing!
