### ISSUE TITLE
Running mysqldump with Promise.all

### ISSUE THREAD

**Issue by Sparticuz** [bradzacher/mysqldump#59]
I'm having some trouble running this with promise.all. It's probably my understanding of promises, but I thought I'd open an issue to see if anyone could help.

I've got an env variable with a comma separated list of databases. I'm trying to dump them all at the same time, so I tried to setup a function that dumped the database (makeMyFiles), then looped through that function and added X number of promises to the array. Then I can call promise.all and, I think, wait for all the promises to resolve. Well, it's returning null, so something is going wrong, but I can't get any meaningful errors.

```TS
'use strict';

interface FileObj {
  path: string;
  fileSizeInBytes: number;
}

import { Context, ScheduledEvent } from 'aws-lambda';
// @ts-ignore
import { unlink, existsSync, mkdirSync, Stats, statSync } from 'fs';
import { sendMyFile } from './sendMyFile';
import { join } from 'path';
import { tarMyDirectory } from './tarMyDirectory';
import mysqldump from 'mysqldump';

const makeMyFiles = async (schema: string, time: string) => {
  const path = join('/','tmp', time, `${schema}_${time}.sql`);

  console.log(schema, path);

  // Dump the database to a file
  const options = {
    connection: {
      charset: 'utf8mb4_unicode_ci',
      database: schema,
      host: process.env.HOST_NAME,
      password: process.env.DB_PASS,
      user: process.env.DB_USER
    },
    dumpToFile: path
  };

  mysqldump(options).then(()=>{
    // Get File Stats
    const stats: Stats = statSync(path);
    const fileSizeInBytes: number = stats.size;
    const file: FileObj = { path, fileSizeInBytes };
    console.log(schema, file);
    return file;
  }).catch((err)=>{
    console.error(err);
    return err;
  });
};

module.exports.rdsdumpToS3 = async (event: ScheduledEvent, context: Context) => {

  // Get time
  const timestring: string = new Date().toISOString().split('.')[0].replace(/-/g,'.').replace(/:/g,'.');

  const path: string = join('/','tmp', timestring);
  if (!existsSync(path)) {
    mkdirSync(path);
  }

  // Create the promises
  const promises: any = [];
  // Loop through all databases at once
  process.env.DB_NAME.split(/\s*,\s*/).forEach((schema) => {
    // Push the promise
    promises.push(makeMyFiles(schema,timestring));
  });

  // Resolve all the promises
  Promise.all(promises)
    .then((results) => {
      console.log('Promises are done');
      // We have run all the dumps, now I should have a 'path' folder with all the schemas in it,
      // now, we should zip them all up and send that to s3
      // First, we need to tar up the directory
       tarMyDirectory(path, timestring);
       // Now send the file to S3
       sendMyFile(path);
      return {
        success: true
      }
    }).catch((e)=>{
      console.error(e);
      return {
        e
      };
    });
};

**Comment by Sparticuz** [comment]
OK, I did fix this issue, and had my new code successfully run when there is only one database being dumped, However, as soon as I add a second one, it just hangs on the mysqldump. Both promises start, but never finish.

**Comment by Sparticuz** [comment]
Actually, an error just popped up for me. It's because of my geometry fields. Looks like I need #52 merged in to get this to work for me.

**Comment by bradzacher** [comment]
I've just taken back ownership of this repo from my previous company, as they didn't have resources to maintain it after I left them.

I'll be looking into cleaning up PRs/Issues after the holidays.

---

When commenting with a code block on github, you can add a language specifier to the first set of backticks, so github knows which highlighter to use.

I.e. below, I used ` ```TS ` to highlight as typescript.

Just an FYI with your code.

You've got a mishmash of ES6 module code, and commonjs module code.
- You don't need `'use strict';`
  - es6 modules are strict by default (and typescript should transpile in the statement for you if you don't target es6 with it).
- use `export const rdsdumpToS3 = ...` instead of `module.exports.rdsdumpToS3`
  - if you ever target a non-commonjs module system - this line will break your codebase.
- actually use async/await
  - you've declared your function as asynchronous but haven't actually got any awaits.
  - you can change your Promise.all code to:

```TS
try {
	const results = await Promise.all(promises);
    console.log('Promises are done');
    // We have run all the dumps, now I should have a 'path' folder with all the schemas in it,
    // now, we should zip them all up and send that to s3
    // First, we need to tar up the directory
    tarMyDirectory(path, timestring);
    // Now send the file to S3
    sendMyFile(path);
    return {
      success: true
    }
} catch (e) {
    console.error(e);
    return {
      e
    };
}
```

**Comment by Sparticuz** [comment]
Thanks for the clarifications and the help! I was able to cleanup a lot of the code based on your recommendations. My only bug (beside the geometry type), is that I'm running out of space on Lambda! We can only use 512mb in /tmp. I will probably need to refactor to have the dump go to RAM, then tar & gzip from memory.

**Comment by bradzacher** [comment]
depending on the lambda tier you're using, you might run out of RAM!
That's why I added streaming to file support in v2; because for large DBs it was using too much RAM, and died before it could write it to file.

Worst case you will have to bump up to a higher lambda tier. I think one of the highest has ~2gb of ram? Should be enough!

**Comment by Sparticuz** [comment]
Dumping a 117mb database took 1g of ram for streaming, and 400mb of ram to dump it to disk. Still working on getting my 200mb database to dump correctly, lambda keeps timing out when running the larger schema (it also contains the geometry types, so that might be crashing something)
