### ISSUE TITLE
Project Update

### ISSUE THREAD

**Issue by bradzacher** [bradzacher/mysqldump#60]
Hi folks!

Sorry about the lack of maintership for the last few months.

I acquired ownership of the package and moved it into my previous company's namespace when I was working there, and maintained it until I left in July.
Unfortunately they no longer had the free resources to maintain an open source project, so it has languished in the mean time.

I have just (on 23rd Dec) taken back ownership of this repo into my own open source portfolio.
I'll be looking into reviewing/merging PRs and triaging Issues after the holidays.

Thanks for the patience!

-Brad

**Comment by creadicted** [comment]
Sound great. What about the open pull requests. Any time to check them? 
#52 #56 and #57 seem fine without a doubt.

**Comment by bradzacher** [comment]
Unfortunately between the work, appendicitis, typescript-eslint, I haven't had much spare OSS time 😢.
A few of the core maintainers on typescript-eslint had to step back for a short while due to personal reasons, so majority of my OSS time has been just reviewing PRs and responding to issues over there.

I've got the notifications for everything on this repo sitting on my dashboard waiting for me to get to. I'll prioritise them and get to them next, hopefully today or tomorrow.
