### ISSUE TITLE
SyntaxError.Unexpected identifier

### ISSUE THREAD

**Issue by bugToaster** [bradzacher/mysqldump#62]
I am getting this following error on linux os

(function (exports, require, module, __filename, __dirname) { import mysqldump from 'mysqldump'
                                                                     ^^^^^^^^^

SyntaxError: Unexpected identifier

**Comment by bradzacher** [comment]
That looks like a problem with whatever bundler/compiler you're using.

The end of the line you provided: `import mysqldump from 'mysqldump'`
We don't import our own package into our package, so the problem is with your code somewhere...
