### ISSUE TITLE
View schemas occur prior to referenced tables in dumps

### ISSUE THREAD

**Issue by ghost** [bradzacher/mysqldump#65]
I have a db with view names that are alphabetically prior to the tables that they reference, so when trying to load the dump files it would die with an error when it came to the CREATE OR REPLACE VIEW.

I patched it locally by sorting the return value of getSchemaDumps to put views after tables. PR is on the way.

**Comment by MikPak** [comment]
Thanks for this fix and nice coincidence that you happened to post this at the very same moment I noticed this problem lol.

I had same problem where a view referenced to a table that was defined later in the dump file. Can confirm this to work.
