### ISSUE TITLE
Add CREATE DATABASE and DB selection before dump

### ISSUE THREAD

**Issue by MikPak** [bradzacher/mysqldump#67]
Is it currently possible to add statement like this before the actual dump?

	DROP DATABASE   IF     EXISTS base;
	CREATE DATABASE IF NOT EXISTS base;
	USE base;

I've large list of different databases that I want to dump and this would help importing them in bulk to the new database.

**Comment by bradzacher** [comment]
Definitely happy to have it added as an option!
