### ISSUE TITLE
Amazon S3

### ISSUE THREAD

**Issue by timcullen** [bradzacher/mysqldump#7]
Great module.

any plans to add an option to save the mysql dump to s3 instead of to local disk file?  looks like this might be changed by expanding line 151?

Alternatively, could you have on option to turn off the file creation on line 151 and instead return the datadump in the callback so the user can do the s3 upload themselves?

Tim

**Comment by webcaetano** [comment]
That's an interesting idea. 
In my case i get the .sql file and send it via email. 

Currently i'm nothing having to much time.Maybe soon. 
Will mark as help wanted for an PR.

**Comment by Akamaozu** [comment]
@timcullen @webcaetano 

here's the functionality you're looking for: https://github.com/webcaetano/mysqldump/pull/8

**Comment by webcaetano** [comment]
Partially fixed on #8
