### ISSUE TITLE
Special characters on JSON field types are not exported correctly

### ISSUE THREAD

**Issue by abelrgr** [bradzacher/mysqldump#70]
On the dump for the JSON field Types, the special characters does not export well :(

Original
```json
["AF", "Afġānistān"]
```
Exported:
```json
["AF", "AfÄ¡ÄnistÄn"]
```

Pd. Sorry for my bad english

**Comment by cioddi** [comment]
Have you tried a different charset.
default is UTF8_GENERAL_CI which does not contain those special characters, maybe it works if you set ```charset: 'UTF8_UNICODE_CI',```

If that does not help there is probably more information required to answer this question.

**Comment by Kosta-Github** [comment]
I am using `charset: 'utf8mb4'` in the `mysql` connection parameters which also solved issues with `emojis`... :-)

**Comment by xiongsongsong** [comment]
![image](https://user-images.githubusercontent.com/342509/64109521-524a8900-cdb2-11e9-97a0-5c709470846f.png)

I try set utf8mb4 or utf8mb4_unicode_ci, but still fail.
column ```elements``` is json field.

if I use original mysqldump, it's no problem.
