### ISSUE TITLE
SQL formatter is slow and very CPU-intensive

### ISSUE THREAD

**Issue by OJezu** [bradzacher/mysqldump#83]
_.trimEnd used by sql-formatter is very CPU intensive, using mysqldump with formatter disabled vs enabled is difference of 38s vs ~300s, and CPU usage of ~35% vs 100% in my case.

|  \    | CPU       | time   |
| --------------- | ---------- | ------- |
| Formatter     | 100%    | 318s  |
| No formatter | ~35%    | 38s    |

My dump does contain non-trivial amount of data.

I think formatter should be disabled by default.

Profile with no formatter:
![image](https://user-images.githubusercontent.com/3941091/61993561-f92e5d80-b06d-11e9-818f-ce87aa27b7dd.png)
![image](https://user-images.githubusercontent.com/3941091/61993569-106d4b00-b06e-11e9-980e-95f0cd8f92be.png)

Profile with formatter (default):
![image](https://user-images.githubusercontent.com/3941091/61993650-1d3e6e80-b06f-11e9-9170-403fb0c3440b.png)
![image](https://user-images.githubusercontent.com/3941091/61993637-f1bb8400-b06e-11e9-9a01-c5cd9cfb3e2c.png)

**Comment by muoto** [comment]
What options can be passed in to disable the formatter?

**Comment by bradzacher** [comment]
There is an option - `format`.
Please read the readme for configuration options.
It's not disabled by default as not all usecases want an unreadable dump.

If your dump is large enough and this is causing you issues. Feel free to turn it off.
