### ISSUE TITLE
Compression does not work

### ISSUE THREAD

**Issue by rcupic** [bradzacher/mysqldump#86]
compressFile: true does not compress file and gunzip says that file is not in gzip format.

```
mysqldump({
    connection: {
        host: 'localhost',
        user: dbConfig.user,
        password: dbConfig.password,
        database: dbConfig.database
    },
    dumpToFile: `../MySQLBackup/${fName}.sql.gz`,
    compressFile: true,
}, err => {
    if(err)
        console.log(err);
    process.exit(0);
});
```

Mysqldump version is 2.3.0

**Comment by bradzacher** [comment]
File compression was added in 3.1.0.
Please read the release notes, and upgrade your version if you to use it.

https://github.com/bradzacher/mysqldump/releases
