### ISSUE TITLE
Process hangs after dump

### ISSUE THREAD

**Issue by zmarouf** [bradzacher/mysqldump#9]
Hello!

I tried running a simple test with Node 4.2.1, 5.11.0 and 6.1.1 and the process hangs without ever exiting after dumping the file in all versions.
![image](https://cloud.githubusercontent.com/assets/4321056/15430783/235a799c-1ea7-11e6-85af-28b188b31b2b.png)
I put a call to process.exit in the callback for now but that's kind of unclean.

**Comment by webcaetano** [comment]
Hmm... The last version passed without any problem
https://travis-ci.org/webcaetano/mysqldump/jobs/131506940

I will review that anytime soon.

**Comment by Akamaozu** [comment]
@zmarouf I noticed it too. 

node 6.1.0
npm 3.8.6

I figured it wasn't closing its mysql connection. 
After closing the connection, the hanging disappeared.

See if it works for you too: https://github.com/Akamaozu/mysqldump/tree/fix-hanging-connection

**Comment by webcaetano** [comment]
@Akamaozu i'll review that soon.

**Comment by webcaetano** [comment]
also i think it's a good idea add the new versions of node to travis

**Comment by webcaetano** [comment]
@Akamaozu merged. published 1.1.1 with `mysql.end`
Also added 6.2.0 and 4.4.4 to travis for auto tests.

Commits related
417a2587c970fef48d58f020d30c5616c5e4a612
8c6ebedefb98112af4aa328b71be06948e01aa3c
a860cbdb6174b4ecab86cdc0e17a5d410cf33fa9
417a2587c970fef48d58f020d30c5616c5e4a612
