### ISSUE TITLE
Encoding issues and 'SET NAME <encoding>'

### ISSUE THREAD

**Issue by Efulefu** [bradzacher/mysqldump#90]
Hello,

I've encountered the dreaded encoding errors dumping/importing using this library, and finally fixed them by manually adding 'SET NAME utf8mb4' to the top of the file.
Would it be appropriate to somehow automate this process?
For example retrieving the desired encoding from the ConnectionOptions.charset option?
Or running some sort of 'GET NAME' query and parsing its' results?

**Comment by bradzacher** [comment]
Happy to accept a PR
