### ISSUE TITLE
Old AWS RDS certificates - updating mysql2 library version?

### ISSUE THREAD

**Issue by krasnyd** [bradzacher/mysqldump#99]
On March 4, 2020 AWS [updated customer certificates](https://aws.amazon.com/blogs/database/amazon-rds-customers-update-your-ssl-tls-certificates-by-february-5-2020/). New certificates are included in [mysql2 ](https://github.com/sidorares/node-mysql2)version >=2.0.0 (according to their [changelog](https://github.com/sidorares/node-mysql2/blob/master/Changelog.md)). Would it be possible to use newer version of mysql2 dependency?

**Comment by bradzacher** [comment]
happy to accept a PR
